---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/kylebra2/public_html/dev/site_test/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R font-awesome $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp datascience.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp my.ico $DEPLOYPATH